export const CHANGE_BANNERS = "CHANGE_BANNERS"
export const CHANGE_HOT_RECOMMENDS = "CHANGE_HOT_RECOMMENDS"
export const CHANGE_NEW_ALBUMS = "CHANGE_NEW_ALBUMS"

export const CHANGE_UP_RANKING = "CHANGE_UP_RANKING"
export const CHANGE_NEW_RANKING = "CHANGE_NEW_RANKING"
export const CHANGE_ORIGIN_RANKING = "CHANGE_ORIGIN_RANKING"
export const CHANGE_SETTLED_SINGER = "change_settled_singer"